stages:
    - Compile
    - Test
    - Test install

variables:
    IMAGE_PREFIX: "gitlab.lrz.de:5005/sdr/docker-images/"
    GIT_SUBMODULE_STRATEGY: recursive

cache:
    key: extern-${CI_COMMIT_REF_SLUG}-${CI_JOB_NAME}
    paths:
        - extern/*

.tmpl_build: &tmpl_build
    tags: [build]
    dependencies: []
    stage: Compile
    script:
        - mkdir build
        - cd build
        - cmake -DCCSDS_BUILD_DEPS=On -DCMAKE_INSTALL_PREFIX=/usr/local ../
        - make
    artifacts:
        paths:
            - build

.tmpl_test: &tmpl_test
    stage: Test
    tags: [test]
    script:
        - cd build
        - ctest --repeat-until-fail 10 --output-on-failure

.tmpl_install: &tmpl_install
    stage: Test install
    tags: [test]
    script:
        - cd build
        - make install

########################################################################################################################
#####
#####  Stage: Compile
#####
########################################################################################################################

Clang Build:
    <<: *tmpl_build
    image: "${IMAGE_PREFIX}alpine-clang-gnuradio:3.8"

GCC Build:
    <<: *tmpl_build
    image: "${IMAGE_PREFIX}alpine-gcc-gnuradio:3.8"


########################################################################################################################
#####
#####  Stage: Test
#####
########################################################################################################################

Clang Test:
    <<: *tmpl_test
    image: "${IMAGE_PREFIX}alpine-clang-gnuradio:3.8"
    dependencies: [Clang Build]
    needs: [Clang Build]

GCC Test:
    <<: *tmpl_test
    image: "${IMAGE_PREFIX}alpine-gcc-gnuradio:3.8"
    dependencies: [GCC Build]
    needs: [GCC Build]


########################################################################################################################
#####
#####  Stage: Install
#####
########################################################################################################################

Clang Install:
    <<: *tmpl_install
    image: "${IMAGE_PREFIX}alpine-clang-gnuradio:3.8"
    dependencies: [Clang Build]
    needs: [Clang Build]

GCC Install:
    <<: *tmpl_install
    image: "${IMAGE_PREFIX}alpine-gcc-gnuradio:3.8"
    dependencies: [GCC Build]
    needs: [GCC Build]

