/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(add_asm.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(5784459dab7cf68ff8db003e2c94a950)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ccsds/add_asm.h>
// pydoc.h is automatically generated in the build directory
#include <add_asm_pydoc.h>

void bind_add_asm(py::module& m)
{

    using add_asm = ::gr::ccsds::add_asm;


    py::class_<add_asm,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<add_asm>>(m, "add_asm", D(add_asm))

        .def(py::init(&add_asm::make),
             py::arg("ASM"),
             py::arg("frame_len"),
             D(add_asm, make))


        ;
}
