/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(blob_msg_source_b.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(b12166ab3a1d04ef2d6ce9a4d3aaefbd)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ccsds/blob_msg_source_b.h>
// pydoc.h is automatically generated in the build directory
#include <blob_msg_source_b_pydoc.h>

void bind_blob_msg_source_b(py::module& m)
{

    using blob_msg_source_b = ::gr::ccsds::blob_msg_source_b;


    py::class_<blob_msg_source_b,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<blob_msg_source_b>>(
        m, "blob_msg_source_b", D(blob_msg_source_b))

        .def(py::init(&blob_msg_source_b::make),
             py::arg("blob_len"),
             py::arg("length_tag_name"),
             D(blob_msg_source_b, make))


        ;
}
