/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(constellation_ccsds_qpsk_axis.h) */
/* BINDTOOL_HEADER_FILE_HASH(b5e5869e9b8cacf5f73fac229550535d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ccsds/constellation_ccsds_qpsk_axis.h>
// pydoc.h is automatically generated in the build directory
#include <constellation_ccsds_qpsk_axis_pydoc.h>

void bind_constellation_ccsds_qpsk_axis(py::module& m)
{

    using constellation_ccsds_qpsk_axis = ::gr::ccsds::constellation_ccsds_qpsk_axis;


    py::class_<constellation_ccsds_qpsk_axis,
               gr::digital::constellation,
               std::shared_ptr<constellation_ccsds_qpsk_axis>>(
        m, "constellation_ccsds_qpsk_axis", D(constellation_ccsds_qpsk_axis))

        .def(py::init(&constellation_ccsds_qpsk_axis::make),
             D(constellation_ccsds_qpsk_axis, make))


        .def("decision_maker",
             &constellation_ccsds_qpsk_axis::decision_maker,
             py::arg("sample"),
             D(constellation_ccsds_qpsk_axis, decision_maker))


        .def("calc_soft_dec",
             &constellation_ccsds_qpsk_axis::calc_soft_dec,
             py::arg("sample"),
             py::arg("npwr"),
             D(constellation_ccsds_qpsk_axis, calc_soft_dec))

        ;
}
