/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(conv_encode27_bb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(fba76ec79c4e077e80b3d39279aab6fc)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ccsds/conv_encode27_bb.h>
// pydoc.h is automatically generated in the build directory
#include <conv_encode27_bb_pydoc.h>

void bind_conv_encode27_bb(py::module& m)
{

    using conv_encode27_bb = ::gr::ccsds::conv_encode27_bb;


    py::class_<conv_encode27_bb,
               gr::block,
               gr::basic_block,
               std::shared_ptr<conv_encode27_bb>>(
        m, "conv_encode27_bb", D(conv_encode27_bb))

        .def(py::init(&conv_encode27_bb::make),
             py::arg("gen_poly_c1"),
             py::arg("gen_poly_c2"),
             py::arg("puncturing_type"),
             D(conv_encode27_bb, make))


        ;


    py::module m_conv_puncturing27 = m.def_submodule("conv_puncturing27");
}
