/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(conv_decode27.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(de24e431162f3802304d305ba711ed58)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ccsds/conv_decode27.h>
// pydoc.h is automatically generated in the build directory
#include <conv_decode27_pydoc.h>

void bind_conv_decode27(py::module& m)
{

    using conv_decode27 = ::gr::ccsds::conv_decode27;


    py::class_<conv_decode27,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<conv_decode27>>(m, "conv_decode27", D(conv_decode27))

        .def(py::init(&conv_decode27::make),
             py::arg("gen_poly_c1"),
             py::arg("gen_poly_c2"),
             py::arg("puncturing_type"),
             py::arg("block_len"),
             py::arg("ASM"),
             D(conv_decode27, make))


        ;


    py::module m_conv_puncturing27 = m.def_submodule("conv_puncturing27");
}
