/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(decoder_verbosity.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(a7ec93429ee3b6b03a9fd8ffb64c7404)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ccsds/decoder_verbosity.h>
// pydoc.h is automatically generated in the build directory
#include <decoder_verbosity_pydoc.h>

void bind_decoder_verbosity(py::module& m)
{


    py::enum_<::gr::ccsds::decoder_verbosity_t>(m, "decoder_verbosity_t")
        .value("DECODER_VERBOSITY_QUIET",
               ::gr::ccsds::decoder_verbosity_t::DECODER_VERBOSITY_QUIET) // 0
        .value("DECODER_VERBOSITY_DROPPED",
               ::gr::ccsds::decoder_verbosity_t::DECODER_VERBOSITY_DROPPED) // 1
        .value("DECODER_VERBOSITY_FAILED",
               ::gr::ccsds::decoder_verbosity_t::DECODER_VERBOSITY_FAILED) // 2
        .value("DECODER_VERBOSITY_ALL",
               ::gr::ccsds::decoder_verbosity_t::DECODER_VERBOSITY_ALL) // 3
        .value("DECODER_VERBOSITY_DEBUG",
               ::gr::ccsds::decoder_verbosity_t::DECODER_VERBOSITY_DEBUG) // 4
        .export_values();

    py::implicitly_convertible<int, ::gr::ccsds::decoder_verbosity_t>();
}
