/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(frame_generation_config.h) */
/* BINDTOOL_HEADER_FILE_HASH(cf40e29ad1747eb9b59b65565ff0646e)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ccsds/frame_generation_config.h>
// pydoc.h is automatically generated in the build directory
#include <frame_generation_config_pydoc.h>

void bind_frame_generation_config(py::module& m)
{

    using frame_generation_config = ::gr::ccsds::frame_generation_config;


    py::class_<frame_generation_config, std::shared_ptr<frame_generation_config>>(
        m, "frame_generation_config", D(frame_generation_config))

        .def(py::init(&frame_generation_config::make),
             py::arg("num_frames_before"),
             py::arg("num_frames_after"),
             py::arg("min_correlation_pct_primary") = 0.F,
             py::arg("min_correlation_pct_secondary") = 0.F,
             D(frame_generation_config, make))


        .def("frames_before",
             &frame_generation_config::frames_before,
             D(frame_generation_config, frames_before))


        .def("frames_after",
             &frame_generation_config::frames_after,
             D(frame_generation_config, frames_after))


        .def("min_correlation_primary_pct",
             &frame_generation_config::min_correlation_primary_pct,
             D(frame_generation_config, min_correlation_primary_pct))


        .def("min_correlation_secondary_pct",
             &frame_generation_config::min_correlation_secondary_pct,
             D(frame_generation_config, min_correlation_secondary_pct))


        ;
}
