/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(mpsk_mod_bc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(ba5d72dd22b93e5fd2e03244e37ca23e)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ccsds/mpsk_mod_bc.h>
// pydoc.h is automatically generated in the build directory
#include <mpsk_mod_bc_pydoc.h>

void bind_mpsk_mod_bc(py::module& m)
{

    using mpsk_mod_bc = ::gr::ccsds::mpsk_mod_bc;


    py::class_<mpsk_mod_bc,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<mpsk_mod_bc>>(m, "mpsk_mod_bc", D(mpsk_mod_bc))

        .def(py::init(&mpsk_mod_bc::make), py::arg("M"), D(mpsk_mod_bc, make))


        ;
}
