/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(mpsk_detector_soft_cf.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(75ada65b636670966ad4f9e6efd5afff)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ccsds/mpsk_detector_soft_cf.h>
// pydoc.h is automatically generated in the build directory
#include <mpsk_detector_soft_cf_pydoc.h>

void bind_mpsk_detector_soft_cf(py::module& m)
{

    using mpsk_detector_soft_cf = ::gr::ccsds::mpsk_detector_soft_cf;


    py::class_<mpsk_detector_soft_cf,
               gr::sync_interpolator,
               std::shared_ptr<mpsk_detector_soft_cf>>(
        m, "mpsk_detector_soft_cf", D(mpsk_detector_soft_cf))

        .def(py::init(&mpsk_detector_soft_cf::make),
             py::arg("M"),
             py::arg("offset_const_points") = 0.,
             D(mpsk_detector_soft_cf, make))


        ;
}
