/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pack_bit_to_bytes.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(f0c96a2a02572b198bbe18bc84158f6a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ccsds/pack_bit_to_bytes.h>
// pydoc.h is automatically generated in the build directory
#include <pack_bit_to_bytes_pydoc.h>

void bind_pack_bit_to_bytes(py::module& m)
{

    using pack_bit_to_bytes = ::gr::ccsds::pack_bit_to_bytes;


    py::class_<pack_bit_to_bytes, gr::sync_decimator, std::shared_ptr<pack_bit_to_bytes>>(
        m, "pack_bit_to_bytes", D(pack_bit_to_bytes))

        .def(py::init(&pack_bit_to_bytes::make), D(pack_bit_to_bytes, make))


        ;
}
