/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pll_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(0f070b51564fce8bd6ebc7c1faf4d888)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ccsds/pll_cc.h>
// pydoc.h is automatically generated in the build directory
#include <pll_cc_pydoc.h>

void bind_pll_cc(py::module& m)
{

    using pll_cc = ::gr::ccsds::pll_cc;


    py::class_<pll_cc, gr::block, gr::basic_block, std::shared_ptr<pll_cc>>(
        m, "pll_cc", D(pll_cc))

        .def(py::init(&pll_cc::make),
             py::arg("m"),
             py::arg("loop_bandwidth"),
             D(pll_cc, make))


        ;
}
