/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(reversebits.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(5f9922057482f959917ddfbe506202cc)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ccsds/reversebits.h>
// pydoc.h is automatically generated in the build directory
#include <reversebits_pydoc.h>

void bind_reversebits(py::module& m)
{

    using reversebits = ::gr::ccsds::reversebits;


    py::class_<reversebits,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<reversebits>>(m, "reversebits", D(reversebits))

        .def(py::init(&reversebits::make),
             py::arg("msg_length"),
             py::arg("reverse_indices"),
             D(reversebits, make))


        ;
}
