/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(rs_decode.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d8f5e0d172775f6fb5ce89bdc5ffe8c3)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ccsds/rs_decode.h>
// pydoc.h is automatically generated in the build directory
#include <rs_decode_pydoc.h>

void bind_rs_decode(py::module& m)
{

    using rs_decode = ::gr::ccsds::rs_decode;


    py::class_<rs_decode, gr::block, gr::basic_block, std::shared_ptr<rs_decode>>(
        m, "rs_decode", D(rs_decode))

        .def(py::init(&rs_decode::make),
             py::arg("I"),
             py::arg("representation"),
             py::arg("verbosity"),
             D(rs_decode, make))


        ;
}
