/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(rs_encode.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d5ee55b08a53b211cfeeecca1f5a58e3)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ccsds/rs_encode.h>
// pydoc.h is automatically generated in the build directory
#include <rs_encode_pydoc.h>

void bind_rs_encode(py::module& m)
{

    using rs_encode = ::gr::ccsds::rs_encode;


    py::class_<rs_encode, gr::block, gr::basic_block, std::shared_ptr<rs_encode>>(
        m, "rs_encode", D(rs_encode))

        .def(py::init(&rs_encode::make), py::arg("I"), D(rs_encode, make))


        ;
}
