/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(snr_est.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(89d1b6fea1ab92f5f324bc44f38d82e0)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ccsds/snr_est.h>
// pydoc.h is automatically generated in the build directory
#include <snr_est_pydoc.h>

void bind_snr_est(py::module& m)
{

    using snr_est = ::gr::ccsds::snr_est;


    py::class_<snr_est, std::shared_ptr<snr_est>>(m, "snr_est", D(snr_est))

        .def(py::init<>(), D(snr_est, snr_est, 0))
        .def(py::init<gr::ccsds::snr_est const&>(),
             py::arg("arg0"),
             D(snr_est, snr_est, 1))


        .def("update",
             &snr_est::update,
             py::arg("num_inputs"),
             py::arg("input"),
             D(snr_est, update))


        .def("get_snr", &snr_est::get_snr, D(snr_est, get_snr))


        .def("signal_lin", &snr_est::signal_lin, D(snr_est, signal_lin))


        .def("noise_lin", &snr_est::noise_lin, D(snr_est, noise_lin))

        ;
}
