/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(snr_estimation_cf.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(336f733c9cbaf9df251bdd8f9635bdb0)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ccsds/snr_estimation_cf.h>
// pydoc.h is automatically generated in the build directory
#include <snr_estimation_cf_pydoc.h>

void bind_snr_estimation_cf(py::module& m)
{

    using snr_estimation_cf = ::gr::ccsds::snr_estimation_cf;


    py::class_<snr_estimation_cf, gr::sync_decimator, std::shared_ptr<snr_estimation_cf>>(
        m, "snr_estimation_cf", D(snr_estimation_cf))

        .def(py::init(&snr_estimation_cf::make),
             py::arg("decimation"),
             D(snr_estimation_cf, make))


        ;
}
