/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(softbits_msg_to_bytes_b.h) */
/* BINDTOOL_HEADER_FILE_HASH(03a12d9b162d865273362bd82208b2fe)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ccsds/softbits_msg_to_bytes_b.h>
// pydoc.h is automatically generated in the build directory
#include <softbits_msg_to_bytes_b_pydoc.h>

void bind_softbits_msg_to_bytes_b(py::module& m)
{

    using softbits_msg_to_bytes_b = ::gr::ccsds::softbits_msg_to_bytes_b;


    py::class_<softbits_msg_to_bytes_b,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<softbits_msg_to_bytes_b>>(
        m, "softbits_msg_to_bytes_b", D(softbits_msg_to_bytes_b))

        .def(py::init(&softbits_msg_to_bytes_b::make), D(softbits_msg_to_bytes_b, make))


        ;
}
