/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(softbittobit.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(a5c007fc9c790b8c9879418723e5671d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ccsds/softbittobit.h>
// pydoc.h is automatically generated in the build directory
#include <softbittobit_pydoc.h>

void bind_softbittobit(py::module& m)
{

    using softbittobit = ::gr::ccsds::softbittobit;


    py::class_<softbittobit,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<softbittobit>>(m, "softbittobit", D(softbittobit))

        .def(py::init(&softbittobit::make), D(softbittobit, make))


        ;
}
