/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(sort_frames.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(296f68bc6353ec5c73e52e4831fd2171)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ccsds/sort_frames.h>
// pydoc.h is automatically generated in the build directory
#include <sort_frames_pydoc.h>

void bind_sort_frames(py::module& m)
{

    using sort_frames = ::gr::ccsds::sort_frames;


    py::class_<sort_frames,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<sort_frames>>(m, "sort_frames", D(sort_frames))

        .def(py::init(&sort_frames::make),
             py::arg("window_size"),
             py::arg("allow_duplicates"),
             py::arg("sort_field"),
             py::arg("score_field"),
             py::arg("pick_highest_score"),
             py::arg("verbosity"),
             D(sort_frames, make))


        ;

    py::enum_<::gr::ccsds::sort_frame_verbosity_t>(m, "sort_frame_verbosity_t")
        .value("SORT_FRAME_OUTPUT_QUIET",
               ::gr::ccsds::sort_frame_verbosity_t::SORT_FRAME_OUTPUT_QUIET) // 0
        .value("SORT_FRAME_OUTPUT_DROPPED",
               ::gr::ccsds::sort_frame_verbosity_t::SORT_FRAME_OUTPUT_DROPPED) // 1
        .value("SORT_FRAME_OUTPUT_DUPLICATE",
               ::gr::ccsds::sort_frame_verbosity_t::SORT_FRAME_OUTPUT_DUPLICATE) // 2
        .value("SORT_FRAME_OUTPUT_ALL",
               ::gr::ccsds::sort_frame_verbosity_t::SORT_FRAME_OUTPUT_ALL) // 3
        .export_values();

    py::implicitly_convertible<int, ::gr::ccsds::sort_frame_verbosity_t>();
}
