/*
 * Copyright 2012 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-ccsds
 *
 * GNU Radio is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 *
 * GNU Radio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with GNU Radio; see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street,
 * Boston, MA 02110-1301, USA.
 */

/*
 * This class gathers together all the test cases for the gr-filter
 * directory into a single test suite.  As you create new test cases,
 * add them here.
 */

#include "qa_ccsds.h"
#include "qa_conv_encode27_aux.h"
#include "qa_orbit_aux.h"
#include "qa_orbit_range_interp.h"
#include "qa_constellation_ccsds_bpsk.h"
#include "qa_constellation_ccsds_qpsk.h"
#include "qa_constellation_ccsds_qpsk_axis.h"
#include "qa_frame_sync_buffer.h"
#include "qa_frame_sync_config.h"

CppUnit::TestSuite *
qa_ccsds::suite()
{
  CppUnit::TestSuite *s = new CppUnit::TestSuite("ccsds");
  s->addTest(gr::ccsds::qa_conv_encode27_aux::suite());
  s->addTest(gr::ccsds::qa_orbit_aux::suite());
  s->addTest(gr::ccsds::qa_orbit_range_interp::suite());
  s->addTest(gr::ccsds::qa::constellation::bpsk::suite());
  s->addTest(gr::ccsds::qa::constellation::qpsk::suite());
  s->addTest(gr::ccsds::qa::constellation::qpsk_axis::suite());
  s->addTest(gr::ccsds::qa_frame_sync_buffer::suite());
  s->addTest(gr::ccsds::qa_frame_sync_config::suite());

  return s;
}
