#ifndef INCLUDED_CCSDS_MPSK_DEMOD2_CB_H
#define INCLUDED_CCSDS_MPSK_DEMOD2_CB_H

#include <ccsds_api.h>
#include <gr_sync_block.h>
#include <gr_complex.h>

class ccsds_mpsk_demod2_cb;

typedef boost::shared_ptr<ccsds_mpsk_demod2_cb> ccsds_mpsk_demod2_cb_sptr;

/*! \brief Create an M-PSK demodulator and return it's shared pointer.
 *
 *  \param M Modulation order of the M-PSK signal.
 *  \param quant_bits Confidence value quantization in bit of the detected
 *	symbols. Must be in the interval [0,8].
 *  \return Shared pointer of the created detector.
 *
 *  If \c quant_bits is zero, only the detected symbols are generated. If set to
 *  nonzero a second output stream at the same rate as the detected symbols will
 *  be generated containing a \c quant_bits bit value representing the
 *  confidence in this detection, where 0 means this symbol is a guess as good
 *  as any other symbol and (2 ^\c quant_bits) - 1 means highest confidence in
 *  the detected symbol.
 *
 *  The confidence value is generated by a linear quantization of the symbol's
 *  squared magnitude in the range from [0.0 to 1.0]. Any symbol with a squared
 *  magnitude higher than 1.0 will have highest confidence as well.
 */
CCSDS_API ccsds_mpsk_demod2_cb_sptr ccsds_make_mpsk_demod2_cb (const unsigned int M, const unsigned char quant_bits=0);

/*! \brief M-PSK demodulator. 
 *  \ingroup receiver
 *
 *  M-PSK demodulation based on the phase of the incomming signal.
 *
 *  The incomming phase is converted to a conteallation point (counting
 *  counterclockwise starting from zero at symbol 1+0j) with the non linear
 *  function:
 *
 *  \code const_point = floor( 0.5*M*fmod( angle/pi + 2, 2) + 0.5 ) \endcode
 *
 *  And then the constellation point is mapped to the actual symbol bit sequence
 *  by a binary to gray code mapping [http://en.wikipedia.org/wiki/Grey_code#Converting_to_and_from_Gray_code]:
 *
 *  \code data = (const_point >> 1) ^ const_point \endcode
 */
class CCSDS_API ccsds_mpsk_demod2_cb : public gr_sync_block
{
private:
	friend CCSDS_API ccsds_mpsk_demod2_cb_sptr ccsds_make_mpsk_demod2_cb (const unsigned int M, const unsigned char quant_bits);

	/*! \brief Public constructor of the M-PSK demodulator
	 *
	 *  \param M Modulation order of the M-PSK signal.
	 *  \param quant_bits Confidence value quantization in bit of the detected
	 *	symbols. Must be in the interval [0,8].
	 *  \sa ccsds_mpsk_demod_cb
	 *
	 *  Demodulate M-PSK modulated symbols back to data bits. This
	 *  demodulator	detects the data bits by a non linear transformation of
	 *  the sample's phase. See \ref ccsds_mpsk_demod_cb for a demodulator
	 *  based on the nearest neighbour principle.
	 *
	 *  The first output stream will output the detected symbols. A second
	 *  output stream at the same rate as the detected symbols will be
	 *  generated containing a \c quant_bits bit value representing the
	 *  confidence in this detection, where 0 means this symbol is a guess as good
	 *  as any other symbol and (2 ^\c quant_bits) - 1 means highest confidence in
	 *  the detected symbol.
	 *
	 *  The confidence value is generated by a linear quantization of the symbol's
	 *  squared magnitude in the range from [0.0 to 1.0]. Any symbol with a squared
	 *  magnitude higher than 1.0 will have highest confidence as well.
	 */
	ccsds_mpsk_demod2_cb (const unsigned int M, const unsigned int quant_bits=0);   // private constructor

	/*! \brief Modulation order. */
	const unsigned int d_M;

	/*! \brief Number of quantization bits for the confidence value. */
	const unsigned char d_QUANT_BITS;

	/*! \brief Maximum value for the confidece value. */
	const unsigned char d_QUANT_MAX;

	/*! \brief Precomputed constant for 2pi with float precision. */
	const float d_TWOPI;

	/*! \brief Array to map binary constellation points to gray coded data
	 *	bits.
	 */
	const unsigned char *map;

	/*! \brief Perform the quantization.
	 *
	 *  \param mag squared magnitude of the sample.
	 *  \return Quantized value in the range from [0,d_QUANT_MAX].
	 */
	unsigned char quant(const float mag) const ;
	
public:

	/*! \brief Public deconstructor */
	~ccsds_mpsk_demod2_cb ();  // public destructor

	int work ( int                         noutput_items,
		gr_vector_const_void_star   &input_items,
		gr_vector_void_star         &output_items);
};

#endif /* INCLUDED_CCSDS_MPSK_DEMOD2_CB_H */
